<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Accept_gsi_355869_826640</name>
   <tag></tag>
   <elementGuidId>5c0eb41e-6fc2-40d9-a21f-886dca5080ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_355869_826640']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_355869_826640</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?type=standart&amp;client_id=1039153326034-mtuh7vnqjct3enp8getd68ljkiio229s.apps.googleusercontent.com&amp;iframe_id=gsi_355869_826640&amp;as=l0Ejo%2FqLjiyom+16Pbk1VQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_355869_826640</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Кнопка &quot;Увайсці праз Google&quot;</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_355869_826640&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_355869_826640']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-auth-button-id']/div/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?type=standart&amp;client_id=1039153326034-mtuh7vnqjct3enp8getd68ljkiio229s.apps.googleusercontent.com&amp;iframe_id=gsi_355869_826640&amp;as=l0Ejo%2FqLjiyom+16Pbk1VQ' and @id = 'gsi_355869_826640' and @title = 'Кнопка &quot;Увайсці праз Google&quot;']</value>
   </webElementXpaths>
</WebElementEntity>
