<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>f6de3f21-58e0-4696-8cb3-f23ad1a0b520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M19 3h-1V1h-2v2H8V1H6v2H5c-1.11 0-1.99.9-1.99 2L3 19c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 16H5V8h14v11zM7 10h5v5H7z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;-webkit- js-focus-visible&quot;]/body[1]/app-root[1]/div[@class=&quot;mat-app-background basic-container&quot;]/div[@class=&quot;content-container&quot;]/main[@class=&quot;app-main&quot;]/app-me-container[1]/div[1]/app-me-time-off[@class=&quot;ng-star-inserted&quot;]/app-me-time-off-create[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page__wrapper&quot;]/div[@class=&quot;page__container&quot;]/div[@class=&quot;page__content form__content&quot;]/form[@class=&quot;form ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;column&quot;]/mat-form-field[@class=&quot;mat-form-field mat-tooltip-trigger ng-tns-c134-18 mat-primary mat-form-field-type-mat-date-range-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c134-18&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c134-18&quot;]/div[@class=&quot;mat-form-field-suffix ng-tns-c134-18 ng-star-inserted&quot;]/mat-datepicker-toggle[@class=&quot;mat-datepicker-toggle ng-tns-c134-18&quot;]/button[@class=&quot;mat-focus-indicator mat-icon-button mat-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-button-wrapper&quot;]/svg[@class=&quot;mat-datepicker-toggle-default-icon ng-star-inserted&quot;]/path[1]</value>
   </webElementProperties>
</WebElementEntity>
